### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by ipwnponies** [edmundmok/mealpy#2]
I tried this out and it's works pretty well. I want to improve this and want to know if you are accepting PR or if I fork this and go off on my own.

Things this project needs:
* License (pick one, I suggest MIT for simplest use case). This allows me to modify and create PRs. Otherwise, I can only use my eyeballs to tell you things.

Ideas I am thinking of:
* Setup instructions
* Caching credentials/cookies, so you don't need to enter password every run
* Caching restaurants for offline querying
* Caching meal items
* Ability to run this adhoc (not everyone needs scheduled runs, some just want to avoid using web interface)

**Comment by edmundmok** [comment]
I haven't used Mealpal in a year, so I'm pleasantly surprised that this script still functions.

I'm not sure if I will be subscribing to it in the near future, so it will be unlikely that this repo will continue to be maintained.

You're welcomed to fork this project and use my code in your own improved version, those sound like good improvements to have.

**Comment by ipwnponies** [comment]
Can you add a license? Without one, this repo defaults to copyright laws aka only rights to view, no rights to modify and distribute (or something to that degree, I am not a lawyer).

How about adding me as a collaborator? This is the canonical repo and adding improvements here will benefit all forks (I already see a forks with same changes I plan to implement, python 3). As well as having me field issues and whatnot. Feel free to decline and I'll continue with a fork.

**Comment by edmundmok** [comment]
Sure, I've added an MIT License to the repo, and also added you as a collaborator.

**Comment by ipwnponies** [comment]
Great, I'm going to close this issue and create PR + tickets to track the other items.
