### ISSUE TITLE
Setup travisci

### ISSUE THREAD

**Issue by ipwnponies** [edmundmok/mealpy#30]
We're starting to see more contributors and we have some tests. Let's set up TravisCI to automatically run tests on PRs, reduces the need to ask if they've ran unit tests, can instead focus on what manual verification was done.

@edmundmok, as the repository owner, can you enable TravisCI? From this [stackoverflow post], I can do the rest of the setup via `travis.yml` file.

[stackoverflow post]: https://stackoverflow.com/a/25867802

**Comment by edmundmok** [comment]
I've enabled it [here](https://travis-ci.org/edmundmok/mealpy).

**Comment by ipwnponies** [comment]
I'm not going to lie, part of my motivation for doing this is to collect all the badges for the README. Because everyone loves badges lol.

![image](https://user-images.githubusercontent.com/4278368/56877659-5f222f00-6a04-11e9-8c65-26f182b99205.png)

**Comment by edmundmok** [comment]
We do need more colors in the README!
