### ISSUE TITLE
Add cli arguments

### ISSUE THREAD

**Issue by ipwnponies** [edmundmok/mealpy#4]
The inputs to the script are hard-coded.

https://github.com/edmundmok/mealpy/blob/9e60e066a53408057bedba882970c485bf5c516d/mealpy.py#L133-L136

Add argparse to get these inputs.

**Comment by edmundmok** [comment]
I am going to explore using [click](https://github.com/pallets/click) instead of just argparse, since it seems to be a better way of managing commands, and we are going to be supporting other commands like displaying restaurants.
